### ISSUE TITLE
Re-enable frame eval: multiprocessing.Process

### ISSUE THREAD

**Issue by Elizaveta239** [fabioz/PyDev.Debugger#129]
Hi! It looks like after the latest changes with re-enabling frame eval debugger, calling to `multiprocessing.Process()` stopped working in frame evaluation mode with Python 3.6. Debugging this code leads to deadlock in a child process:

```
import time
import multiprocessing


def run(name):
    print("argument: ", name)  # breakpoint


if __name__ == '__main__':
    multiprocessing.Process(target=run, args=("arg",)).start()
    time.sleep(5)
```
It might be a merging issue. Could you please check it in PyDev sources as well? I tried to reproduce it in VS Code, but it doesn't work there even in the released October version.
Thank you!

**Comment by fabioz** [comment]
Hi Elizaveta, this seems to work properly for me with the latest master in pydev, so, could be something related to the merge...

As a note, ptvsd (for vscode) has issues with forking and multiprocessing which it handles differently (so, that's a work in progress for it and is not the best test).

Keeping open just because it may be nice to have an automated test for this (if it still hasn't such a test).

**Comment by fabioz** [comment]
One question: did you check on Windows or Linux (I just tested it on Windows, so, would like to double check with you as this could be the reason I didn't reproduce it...).
