### ISSUE TITLE
Re-enable frame eval: breakpoint on the first line doesn't work

### ISSUE THREAD

**Issue by Elizaveta239** [fabioz/PyDev.Debugger#134]
Hi! It looks like after the latest updates in frame eval debugger, breakpoint doesn't work, if it's on the top level and on the first line with code.

```
a = 1  # breakpoint, doesn't work
b = 2
c = 3
``` 

It works fine if it's not on the first line, or if there are other breakpoints in the same frame.

```
a = 1  
b = 2  # breakpoint, works
c = 3
``` 
or 
```
a = 1  # breakpoint, works
b = 2  
c = 3  # breakpoint, works
```

Also, I noticed some interesting effect not only about top-level breakpoints, but also about breakpoints inside functions. If there is only one breakpoint in a frame, debugger uses frame eval (if it's available, of course). But if there are at least 2 breakpoints in the same scope, debugger falls back to tracing. 
As far as I remember there was no such behaviour in the previous implementation. Do you have any reasons for that or is it a bug?

**Comment by fabioz** [comment]
I can't reproduce the first one in the latest master, so, not sure... can you create a pull request with a test case showing the problem?

Regarding the second, I think the issue happens because after a frame becomes traced it doesn't become untraced anymore (I think this was true before, as the main issue fixed was that after a breakpoint was hit in a given frame the whole debugger was much slower than even regular tracing afterwards) -- anyways, I already know about it and have plans to remove that restriction in the future (to go from traced to frame eval mode when possible), but there's still no due date for that.

i.e.: with the code below with 2 breakpoints which are never hit is stays in frame eval mode

```
if False:
    a = 1  # break here
b = 2
if False:
    c = 3  # break here
import sys
print(sys._getframe().f_trace)
print('finished')
```

**Comment by fabioz** [comment]
Thanks for the test case. I just fixed 2 issues reported (skipping a breakpoint in the first line of module when breakpoint line != 1 and properly use frame eval if a second breakpoint is added to the same context).

The case that it still keeps tracing after the first breakpoint is hit in frame eval mode is still there (it's a known issue which I'll fix in the future).
