### ISSUE TITLE
Debugger hits breakpoints in Qt threads regardless of whether qt-support option was set in Python 3.6 and newer

### ISSUE THREAD

**Issue by avli** [fabioz/PyDev.Debugger#143]
The debugger hits breakpoints in Qt threads even if the `qt-support` option isn't passed for Python 3.6 and higher. The code below demonstrates the issue:

```python
from PyQt5 import QtCore
import sys


class AThread(QtCore.QThread):

    def run(self):
        for i in range(3):
            print("ping %d" % i)  # breakpoint


app = QtCore.QCoreApplication([])
thread = AThread()
thread.finished.connect(app.exit)
thread.start()
sys.exit(app.exec_())
```

As far as I understand, we don't expect to hit the breakpoint, but we do. A quick investigation shows that it may have something to do with the fact that in newer Python versions a dummy thread is created when QThread starts.

The original report: [https://youtrack.jetbrains.com/issue/PY-34014](https://youtrack.jetbrains.com/issue/PY-34014)

**Comment by fabioz** [comment]
I think the reason this happens is because in Python 3.6 onwards, when using the frame evaluation mode it doesn't really need to turn on the frame tracing in that frame (because frame evaluation is global and not thread-dependent whereas just plain tracing is thread-dependent, in which case that support is needed).

I must say I don't really see this as a problem though (maybe just add docs saying that from Python 3.6 onwards the support doesn't need to be manually enabled), so, closing this issue.

**Comment by avli** [comment]
Makes sense. Thanks, @fabioz!
