### ISSUE TITLE
Updating PyDev in PyCharm issues

### ISSUE THREAD

**Issue by tynanseltzer** [fabioz/PyDev.Debugger#169]
Hi! I'm trying to fix backporting issues with pydevd.py (specifically the dispose_and_kill_all_pydevd_threads function) which prevents me from connecting two debugging instances at once with PyCharm, see https://youtrack.jetbrains.com/issue/PY-40359. I grabbed the 1.9.0 release from this repo, and replaced the pydev in PyCharm with 1.9.0, but I now have the following error when starting up the debugger.
Traceback (most recent call last):
File "/Applications/CLion.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 3129, in
main()
File "/Applications/CLion.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 2997, in main
dispatcher.connect(host, port)
File "/Applications/CLion.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 2728, in connect
self.reader = DispatchReader(self)
File "/Applications/CLion.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 2748, in init
process_net_command=process_net_command,
TypeError: init() missing 1 required positional argument: 'py_db'

Is there something trivial I'm missing or is grabbing the most recent version from this repo not nearly sufficient? If so, is there another fix to the backporting issue?

**Comment by fabioz** [comment]
Humm, it seems that the issue is that this connection mode isn't really working (it's not really used by PyDev -- it was only added for PyCharm and it seems that there are no test cases which actually check it). 

The fix seems to be simple (just pass the PyDB as the first parameter there -- you can use get_global_debugger())... if you plan to contribute back, please add a test case for it so that this doesn't happen again in the future (tests are in `test_debugger.py` -- in this case as it's a different connection mode, you should do a fixture such as `case_setup` in `debugger_fixtures.py`).

Still, I don't know how PyCharm devs are managing it. I believe they use a fork and not the same version available in `PyDev.Debugger`, so, it's possible that they have other changes that were not contributed back (and thus, just using the master from `PyDev.Debugger` could break other things they expect).

**Comment by tynanseltzer** [comment]
Replacing that line and now the debugger doesn't error, but doesn't stop at any breakpoints, so I'm guessing you're right and they've made substantial changes. Going to close this issue, hopefully Jetbrains takes 1.9.0 at some point in the near future!
