### ISSUE TITLE
If there is no pycharm or vscode, can we use Pydev.Debugger alonely in command line  console mode?

### ISSUE THREAD

**Issue by oldljh** [fabioz/PyDev.Debugger#241]
If there is no pycharm or vscode, can we use Pydev.Debugger alonely in command line  console mode?

**Comment by fabioz** [comment]
The short answer is no, it's not possible to use it in the command line (if you want to do that you probably want to use pdb).

The long answer is that this would be possible to implement, but at this point no one has actually done it (it's be a new client but based on the terminal instead of using a UI).

As a note, you could use it with any client that can communicate using the DAP (Debug Adapter Protocol).
