### ISSUE TITLE
Rendering Template with Chameleon fails with debugger

### ISSUE THREAD

**Issue by Hansa064** [fabioz/PyDev.Debugger#29]
At my company we use chameleon (version 2.8.0) to render html templates from python. Using the PyDev.Debugger to debug the code failes with the error:

File "layout_7dfad0a9ba3acf8fdf769e32117651b6b95707d9.py", line 2, in <module>
ImportError: cannot import name pydev_debugger_exc_info

**Comment by joeyzhao2018** [comment]
I had the same problem and I really spent a whole afternoon trying to dig into the codes. I fixed it by changing another python interpreter. That's right. This is not a problem with chameleon or pyramid etc. Chameleon is merely trying to create the temp file based on the information of your interpreter, though I'm not sure where my python interpreter directs it to look for pydev.

**Comment by lb1a** [comment]
Same over here, complete traceback at https://gist.github.com/lb1a/1235d390ab9a427f233a

**Comment by mlechner** [comment]
As well over her in a Zope/Plone environment. Any solution/reason found?

@lb1a best wishes to the swimming pool

**Comment by fabioz** [comment]
Can you show the actual code to reproduce this issue?

**Comment by lb1a** [comment]
It has been a while. I reported the bug to the jetbrains people because i encountered it with the PyCharm IDE. 
https://youtrack.jetbrains.com/issue/PY-15292#tab=Comments
They seem to have worked around the problem, because i dont encountered this error with the recent versions any longer. But i dont know what they did exactly.
I will see if i can get you any demo code that triggers the bug.

**Comment by fabioz** [comment]
Well, the debugger changed quite a bit in the meanwhile, so, I guess that's Ok (so, will just mark it as closed -- if you find the issue again, pleas report back).
