### ISSUE TITLE
Multithreading with IronPython

### ISSUE THREAD

**Issue by Elizaveta239** [fabioz/PyDev.Debugger#41]
There is a bug with IronPython.
If we put breakpoints on the lines 10 and 14. The debugger stops at the breakpoint on the line 10, but ignores breakpoint on the line 14.  

```
try:
    import thread
except :
    import _thread as thread

import threading

def bar(y):
    z = 100 + y
    print("Z=%d"%z) #breakpoint here

def foo(x):
    y = x + 1
    print("Y=%d"%y) #breakpoint here

    t = threading.Thread(target=bar, args=(y,))
    t.start()


id = thread.start_new_thread(foo, (1,))

while True:
    pass
```

**Comment by fabioz** [comment]
Ok, will take a look at it.

**Comment by fabioz** [comment]
Well, testing with IronPython 2.7.4, this was happening some times to me, but I think that the issue isn't in the debugger, but in the test itself:

The problem is that the object 't' inside method 'foo' can die before it has a chance to run... if you put a 'global t' inside the 'foo' method, it always works for me (can you confirm that?)

**Comment by Elizaveta239** [comment]
You're definitely right! Sorry for disinformation. Interestingly, it never happened to this test before.
Thank you!

**Comment by fabioz** [comment]
I think this happened because of the change in the debugger speed (so, the racing condition started to appear because of that).
